//! The placeholder App stub (login screen, no runner wired). Split out of
//! wiring.rs on size grounds.

use super::*;

use std::cell::{Cell, RefCell};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use houyicoder_protocol::frontend::SessionId;
use houyicoder_protocol::frontend::memory::ToggleState;
use houyicoder_protocol::frontend::model::ModelCatalog;

use crate::history::HistoryNav;
use crate::input::InputField;
use crate::list_pane_state::ListPaneState;
use crate::notifications::NotificationState;
use crate::paste::PasteStore;
use crate::render_cache::RenderCache;
use crate::resume_picker::SessionPickerState;
use crate::scroll::WindowScroll;
use crate::selection::SystemClipboard;
use crate::state::{LiveBlock, MemoryScopeTab, StatusTab, TrustChoice};

#[expect(clippy::too_many_lines, reason = "long by design, kept whole")]
pub fn app() -> App {
    App {
        screen: Screen::Login,
        stage: Stage::Idle,
        pane: Pane::Transcript,
        viewport: ViewportMode::Working,
        prev_viewport: ViewportMode::Working,
        input: InputField::new(),
        history: HistoryNav::default(),
        transcript: transcript(),
        frames: Vec::new(),
        sealed_frames_end: 0,
        sealed_transcript_len: 0,
        verdict_cursor: 0,
        transcript_scroll: TranscriptScroll::default(),
        display_rows_cache: RefCell::new(Vec::new()),
        display_rows_version: Cell::new(u64::MAX),
        transcript_version: Cell::new(0),
        cached_callids: RefCell::new(Vec::new()),
        cached_fold_keys: RefCell::new(Vec::new()),
        cached_expanded_group: RefCell::new(Vec::new()),
        cached_turn_ids: RefCell::new(Vec::new()),
        cached_pre_rendered: RefCell::new(Vec::new()),
        scrolled_from_frame: None,
        search: SearchState::default(),
        search_transcript: Vec::new(),
        search_truncated: false,
        snapshot_log_bytes: 0,
        search_skipped: 0,
        window_mode: false,
        window_anchor: 0,
        window_end: 0,
        frozen_file_size: 0,
        window_scroll: WindowScroll::default(),
        window_skipped: 0,
        indexing: Cell::new(false),
        indexed_bytes: Cell::new(0),
        index_total: Cell::new(0),
        index_done: Cell::new(false),
        trajectory_log: None,
        export_log: None,
        snapshot: None,
        session_lister: None,
        resume_picker: SessionPickerState::default(),
        pending_resume_target: None,
        palette: PaletteState::default(),
        approval: None,
        ask_question: None,
        status: status(),
        spec_ctx: spec_context(),
        spec_clauses: spec_clauses(),
        diff: diff_data(),
        spec_artifact: spec_artifact(),
        plan_artifact: plan_artifact(),
        review: ReviewQueue {
            findings: review_findings(),
            focus: 0,
            audit_trail: audit_trail(),
        },
        console: ConsoleState {
            todos: console_todos(),
        },
        verify_result: verify_result(),
        graph_result: graph_result(),
        memory_entries: memory_entries(),
        memory_toggles: ToggleState {
            auto_memory: true,
            auto_dream: true,
        },
        memory_scope_tab: MemoryScopeTab::All,
        memory_list: ListPaneState::default(),
        worktree_entries: Vec::new(),
        worktree_list: ListPaneState::default(),
        worktree_level: Cell::new(0),
        trajectory_level: Cell::new(0),
        trajectory_cursor: Cell::new(0),
        trajectory_list_len: Cell::new(0),
        trajectory_turn_idx: Cell::new(0),
        trajectory_at_bg: Cell::new(false),
        agents: Default::default(),
        agent_directory: None,
        artifact: ArtifactSession::stub(),
        proposer: StubProposer::new(),
        login_mode: None,
        stage_history: Vec::new(),
        replaying: false,
        quit: false,
        session_id: SessionId::new("test"),
        runtime: None,
        agent_tx: None,
        session: None,
        pending_permission_req_id: Cell::new(None),
        agent_busy: false,
        notifications: NotificationState::default(),
        terminal_focused: true,
        active_run_req_id: Cell::new(None),
        run_started: None,
        session_started_at: None,
        cumulative_tokens: 0,
        cumulative_steps: 0,
        todos_cache: Vec::new(),
        todo_expanded: false,
        todo_completion_at: HashMap::new(),
        last_terminal_rows: Cell::new(24),
        last_transcript_width: Cell::new(0),
        live_assistant_text: String::new(),
        live_active: false,
        live_reasoning_text: String::new(),
        live_block: LiveBlock::None,
        thinking_started_at: None,
        displayed_tokens: Cell::new(0),
        last_delta_at: None,
        running_tools: HashSet::new(),
        bash_progress: HashMap::new(),
        pending_approvals: Vec::new(),
        pending_trust: None,
        trust_choice: TrustChoice::default(),
        pending_trust_req_id: None,
        last_run_input: None,
        pending: Vec::new(),
        selection: Selection::default(),
        transcript_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        queue_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        jump_pill_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_transcript_rows: RefCell::new(Vec::new()),
        last_all_rows: RefCell::new(Vec::new()),
        pane_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_pane_rows: RefCell::new(Vec::new()),
        status_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_status_rows: RefCell::new(Vec::new()),
        status_selection: Selection::default(),
        pane_selection: Selection::default(),
        approval_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_approval_rows: RefCell::new(Vec::new()),
        approval_selection: Selection::default(),
        render_cache: RefCell::new(RenderCache::default()),
        last_row_callids: RefCell::new(Vec::new()),
        expanded_results: HashSet::new(),
        expanded_fold_groups: HashSet::new(),
        expanded_thinking: HashSet::new(),
        expanded_subagents: HashSet::new(),
        teammate_view: None,
        fleet: Default::default(),
        verbose: false,
        turn_seq: 0,
        last_row_fold_keys: RefCell::new(Vec::new()),
        last_row_expanded_group: RefCell::new(Vec::new()),
        last_row_turn_ids: RefCell::new(Vec::new()),
        pasted: PasteStore::default(),
        paste_buffer: None,
        paste_last: None,
        last_cols: Cell::new(80),
        mode_cache: None,
        rules_cache: Vec::new(),
        dirs_cache: Vec::new(),
        ask_before_git_enabled: true,
        context_cache: None,
        sticky_choices: HashMap::new(),
        verdict_log_cache: Vec::new(),
        permission_tab: PermissionTab::Allow,
        permission_cursor: 0,
        permission_input: PermissionInput::None,
        permission_search: String::new(),
        working_dir: cwd_string(),
        status_cache: None,
        last_status_poll: None,
        pending_status_command: false,
        hook_entries: Vec::new(),
        tool_entries: Vec::new(),
        skill_entries: Vec::new(),
        skill_level: Cell::new(0),
        skill_sel: Cell::new(0),
        skill_disabled: HashSet::new(),
        skill_picker_open: false,
        skill_picker_sel: Cell::new(0),
        hooks_level: Cell::new(0),
        hooks_sel: Cell::new(0),
        projected_from_frame: Cell::new(usize::MAX),
        model_tier: "Default".to_string(),
        model_sel: 0,
        model_catalog: ModelCatalog::default(),
        applied_effort: None,
        model_effort: None,
        model_effort_toggled: false,
        status_tab: StatusTab::default(),
        status_name_edit: None,
        last_title: None,
        cancelling: false,
        clipboard: Arc::new(SystemClipboard),
    }
}
