//! The placeholder App stub (login screen, no runner wired). Split out of
//! wiring.rs on size grounds.

use super::*;

#[expect(clippy::too_many_lines, reason = "long by design, kept whole")]
pub fn app() -> App {
    App {
        screen: Screen::Login,
        stage: Stage::Idle,
        pane: Pane::Transcript,
        viewport: ViewportMode::Working,
        prev_viewport: ViewportMode::Working,
        input: crate::input::InputField::new(),
        transcript: transcript(),
        frames: Vec::new(),
        sealed_frames_end: 0,
        sealed_transcript_len: 0,
        verdict_cursor: 0,
        transcript_scroll: TranscriptScroll::default(),
        display_rows_cache: std::cell::RefCell::new(Vec::new()),
        display_rows_version: std::cell::Cell::new(u64::MAX),
        transcript_version: std::cell::Cell::new(0),
        cached_callids: std::cell::RefCell::new(Vec::new()),
        cached_fold_keys: std::cell::RefCell::new(Vec::new()),
        cached_expanded_group: std::cell::RefCell::new(Vec::new()),
        cached_turn_ids: std::cell::RefCell::new(Vec::new()),
        cached_pre_rendered: std::cell::RefCell::new(Vec::new()),
        scrolled_from_frame: None,
        search: SearchState::default(),
        search_transcript: Vec::new(),
        search_truncated: false,
        snapshot_log_bytes: 0,
        search_skipped: 0,
        window_mode: false,
        window_anchor: 0,
        window_end: 0,
        frozen_file_size: 0,
        window_scroll: crate::scroll::WindowScroll::default(),
        window_skipped: 0,
        indexing: std::cell::Cell::new(false),
        indexed_bytes: std::cell::Cell::new(0),
        index_total: std::cell::Cell::new(0),
        index_done: std::cell::Cell::new(false),
        trajectory_log: None,
        export_log: None,
        snapshot: None,
        session_lister: None,
        resume_picker: crate::resume_picker::SessionPickerState::default(),
        pending_resume_target: None,
        palette: PaletteState::default(),
        approval: None,
        ask_question: None,
        status: status(),
        spec_ctx: spec_context(),
        spec_clauses: spec_clauses(),
        diff: diff_data(),
        spec_artifact: spec_artifact(),
        plan_artifact: plan_artifact(),
        review: ReviewQueue {
            findings: review_findings(),
            focus: 0,
            audit_trail: audit_trail(),
        },
        console: ConsoleState {
            todos: console_todos(),
        },
        verify_result: verify_result(),
        graph_result: graph_result(),
        memory_entries: memory_entries(),
        memory_toggles: houyicoder_protocol::frontend::memory::ToggleState {
            auto_memory: true,
            auto_dream: true,
        },
        memory_scope_tab: crate::state::enums::MemoryScopeTab::All,
        memory_list: crate::list_pane_state::ListPaneState::default(),
        worktree_entries: Vec::new(),
        worktree_list: crate::list_pane_state::ListPaneState::default(),
        worktree_level: std::cell::Cell::new(0),
        trajectory_level: std::cell::Cell::new(0),
        trajectory_cursor: std::cell::Cell::new(0),
        trajectory_list_len: std::cell::Cell::new(0),
        trajectory_turn_idx: std::cell::Cell::new(0),
        trajectory_at_bg: std::cell::Cell::new(false),
        agents: agents(),
        agent_directory: None,
        artifact: ArtifactSession::stub(),
        proposer: StubProposer::new(),
        login_mode: None,
        stage_history: Vec::new(),
        replaying: false,
        quit: false,
        session_id: houyicoder_protocol::frontend::SessionId::new("test"),
        runtime: None,
        agent_tx: None,
        session: None,
        pending_permission_req_id: std::cell::Cell::new(None),
        agent_busy: false,
        terminal_focused: true,
        active_run_req_id: std::cell::Cell::new(None),
        run_started: None,
        session_started_at: None,
        cumulative_tokens: 0,
        cumulative_steps: 0,
        todos_cache: Vec::new(),
        todo_expanded: false,
        todo_completion_at: std::collections::HashMap::new(),
        last_terminal_rows: std::cell::Cell::new(24),
        last_transcript_width: std::cell::Cell::new(0),
        live_assistant_text: String::new(),
        live_active: false,
        live_reasoning_text: String::new(),
        live_block: crate::state::enums::LiveBlock::None,
        thinking_started_at: None,
        displayed_tokens: std::cell::Cell::new(0),
        last_delta_at: None,
        running_tools: std::collections::HashSet::new(),
        bash_progress: std::collections::HashMap::new(),
        pending_approvals: Vec::new(),
        last_run_input: None,
        pending: Vec::new(),
        queue_view_open: false,
        queue_focus: 0,
        selection: Selection::default(),
        transcript_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        queue_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        jump_pill_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_transcript_rows: RefCell::new(Vec::new()),
        last_all_rows: RefCell::new(Vec::new()),
        pane_rect: Cell::new(Rect::new(0, 0, 0, 0)),
        last_pane_rows: RefCell::new(Vec::new()),
        pane_selection: Selection::default(),
        render_cache: RefCell::new(crate::render_cache::RenderCache::default()),
        last_row_callids: RefCell::new(Vec::new()),
        expanded_results: HashSet::new(),
        expanded_fold_groups: HashSet::new(),
        expanded_thinking: HashSet::new(),
        expanded_subagents: HashSet::new(),
        teammate_view: None,
        verbose: false,
        turn_seq: 0,
        last_row_fold_keys: RefCell::new(Vec::new()),
        last_row_expanded_group: RefCell::new(Vec::new()),
        last_row_turn_ids: RefCell::new(Vec::new()),
        pasted: crate::paste::PasteStore::default(),
        paste_buffer: None,
        paste_last: None,
        last_cols: std::cell::Cell::new(80),
        mode_cache: None,
        rules_cache: Vec::new(),
        dirs_cache: Vec::new(),
        ask_before_git_enabled: true,
        context_cache: None,
        sticky_choices: std::collections::HashMap::new(),
        verdict_log_cache: Vec::new(),
        permission_tab: PermissionTab::Allow,
        permission_cursor: 0,
        permission_input: PermissionInput::None,
        permission_search: String::new(),
        working_dir: cwd_string(),
        status_cache: None,
        last_status_poll: None,
        pending_status_command: false,
        hook_entries: Vec::new(),
        tool_entries: Vec::new(),
        hooks_level: std::cell::Cell::new(0),
        hooks_sel: std::cell::Cell::new(0),
        projected_from_frame: std::cell::Cell::new(usize::MAX),
        model_tier: "Default".to_string(),
        model_sel: 0,
        model_catalog: houyicoder_protocol::frontend::model::ModelCatalog::default(),
        applied_effort: None,
        model_effort: None,
        model_effort_toggled: false,
        status_tab: crate::state::enums::StatusTab::default(),
        status_name_edit: None,
        last_title: None,
        cancelling: false,
        clipboard: std::sync::Arc::new(crate::selection::SystemClipboard),
    }
}
